project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'',include('solarpanel.urls')),
    url(r'^accounts/login/$', views.login, name='login'),
    url(r'^accounts/logout/$', views.logout, name='logout', kwargs={'next_page': '/'}),
]






if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

solarpanel/urls.py
from django.conf.urls import url

from . import views

app_name = 'solarpanel'

urlpatterns = [

url(r'^$',views.IndexView.as_view(),name='index'),

# list view

url(r'^list/$',views.ContentListView.as_view(),name='list'),

url(r'^banner/detail/(?P<pk>\d+)$',views.ContentDetailView.as_view(),name='contentdetail'),

url(r'^banner/$',views.BannerDetailView.as_view(),name='Banner'),
url(r'^banner/update/(?P<pk>\d+)$',views.BannerUpdateView.as_view(),name='bannerupdate'),
url(r'^banner/delete/(?P<pk>\d+)$',views.BannerDeleteView.as_view(),name='bannerdelete'),

url(r'^projects/$',views.ProjectDetailView.as_view(),name='Project'),
url(r'^projects/update/(?P<pk>\d+)$',views.ProjectsUpdateView.as_view(),name='projectupdate'),
url(r'^projects/delete/(?P<pk>\d+)$',views.ProjectsDeleteView.as_view(),name='projectdelete'),

url(r'^career/$',views.CareerDetailView.as_view(),name='Career'),
url(r'^career/update/(?P<pk>\d+)$',views.CareerUpdateView.as_view(),name='careerupdate'),
url(r'^career/delete/(?P<pk>\d+)$',views.CareerDeleteView.as_view(),name='careerdelete'),

url(r'^team/$',views.TeamDetailView.as_view(),name='Team'),
url(r'^team/update/(?P<pk>\d+)$',views.TeamUpdateView.as_view(),name='teamupdate'),
url(r'^team/delete/(?P<pk>\d+)$',views.TeamDeleteView.as_view(),name='teamdelete'),

url(r'^media/$',views.MediaDetailView.as_view(),name='Media'),
url(r'^media/update/(?P<pk>\d+)$',views.MediaUpdateView.as_view(),name='mediaupdate'),
url(r'^media/delete/(?P<pk>\d+)$',views.MediaDeleteView.as_view(),name='mediadelete'),

]

solarpanel/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class banner(models.Model):

    authorized=models.ForeignKey('auth.User',null=True)
    type=models.IntegerField()
    photo = models.FileField(upload_to='documents/')
    heading = models.CharField(max_length=250,null=True)
    description = models.TextField(null=True)
    openings = models.IntegerField(null=True)
    name = models.CharField(max_length=250,null=True)
    linkfb = models.URLField(null=True)
    linkinsta = models.URLField(null=True)
    linklin = models.URLField(null=True)
    designation= models.CharField(max_length=100,null=True)

solarpanel/views.py
from django.shortcuts import render, get_object_or_404, redirect,HttpResponseRedirect
from django.urls import reverse_lazy
from django.core.urlresolvers import reverse
from .models import banner
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.views.generic import TemplateView, View, CreateView, DetailView, UpdateView, ListView
from django.views.generic.edit import DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin


class IndexView(TemplateView):
    template_name='solarpanel/admin.html'


class ContentListView(ListView):
    model = banner
    template_name = 'solarpanel/content.html'
    context_object_name = 'con'

    def get_queryset(self):
        return banner.objects.order_by('type')


class ContentDetailView(DetailView):
    model = banner
    template_name='solarpanel/contentdetail.html'
    context_object_name='c'

class BannerDetailView(LoginRequiredMixin,CreateView):
    #login_url = '/'
    #redirect_field_name = 'blog/post_detail.html
    template_name='solarpanel/banner.html'
    context_object_name='banner'
    model=banner
    fields = ('type','heading', 'photo','description')
    #success_url =  reverse_lazy('solarpanel:list')

    def post(self, request, *args, **kwargs):
        type=1
        photo = self.request.FILES['photo']
        fs = FileSystemStorage()
        filename = fs.save(photo.name, photo)
        url = fs.url(filename)

        heading = self.request.POST.get('heading')
        description = self.request.POST.get('description')


        #form = self.get_form(type=type, photo=url, heading=heading, description=description)

        form = banner(type=type, photo=url, heading=heading, description=description)
        #super(BannerDetailView, self).form_valid(form)
         #messages.success(request, 'Item created successfully!')
        form.save()

        return HttpResponseRedirect(reverse('solarpanel:list'))



class ProjectDetailView(LoginRequiredMixin,CreateView):
        template_name = 'solarpanel/project.html'
        context_object_name = 'project'
        model = banner
        fields = ('type', 'heading', 'photo', 'description')

        # success_url =  reverse('content')

        def post(self, request, *args, **kwargs):
            type = 2
            photo = self.request.FILES['photo']
            fs = FileSystemStorage()
            filename = fs.save(photo.name, photo)
            url = fs.url(filename)

            heading = self.request.POST.get('heading')
            description = self.request.POST.get('description')
            form = banner(type=type, photo=url, heading=heading, description=description)
            #super(ProjectDetailView, self).form_valid(form)
            # messages.success(request, 'Item created successfully!')
            form.save()

            return HttpResponseRedirect(reverse('solarpanel:list'))

class CareerDetailView(LoginRequiredMixin,CreateView):
    template_name='solarpanel/career.html'
    context_object_name='career'
    model=banner
    fields = ('type','heading', 'photo','description','openings')
    #success_url =  reverse('content')

    def post(self, request, *args, **kwargs):
        type=3
        photo = self.request.FILES['photo']
        fs = FileSystemStorage()
        filename = fs.save(photo.name, photo)
        url = fs.url(filename)

        heading = self.request.POST.get('heading')
        description = self.request.POST.get('description')
        openings = self.request.POST.get('openings')

        #form = self.get_form(type=type, photo=url, heading=heading, description=description)

        form = banner(type=type, photo=url, heading=heading, description=description, openings=openings)
        #super(CareerDetailView, self).form_valid(form)
         #messages.success(request, 'Item created successfully!')
        form.save()

        return HttpResponseRedirect(reverse('solarpanel:list'))



class TeamDetailView(LoginRequiredMixin,CreateView):
    template_name='solarpanel/team.html'
    context_object_name='team'
    model=banner
    fields = ('type','name','linkfb','linkinsta','linklin', 'photo','description','designation')
    #success_url =  reverse('content')

    def post(self, request, *args, **kwargs):
        type=4
        photo = self.request.FILES['photo']
        fs = FileSystemStorage()
        filename = fs.save(photo.name, photo)
        url = fs.url(filename)

        name = self.request.POST.get('name')
        description = self.request.POST.get('description')
        designation = self.request.POST.get('designation')
        linkfb = self.request.POST.get('linkfb')
        linkinsta = self.request.POST.get('linkinsta')
        linklin = self.request.POST.get('linklin')

        #form = self.get_form(type=type, photo=url, heading=heading, description=description)

        form = banner(type=type, photo=url, designation=designation,linkfb=linkfb,linkinsta=linkinsta,linklin=linklin,name=name, description=description)
        #super(TeamDetailView, self).form_valid(form)
         #messages.success(request, 'Item created successfully!')
        form.save()

        return HttpResponseRedirect(reverse('solarpanel:list'))


class MediaDetailView(LoginRequiredMixin,CreateView):
    template_name='solarpanel/media.html'
    context_object_name='media'
    model=banner
    fields = ('type','heading', 'photo','description')
    #success_url =  reverse('content')

    def post(self, request, *args, **kwargs):
        type=5
        photo = self.request.FILES['photo']
        fs = FileSystemStorage()
        filename = fs.save(photo.name, photo)
        url = fs.url(filename)

        heading = self.request.POST.get('heading')
        description = self.request.POST.get('description')


        #form = self.get_form(type=type, photo=url, heading=heading, description=description)

        form = banner(type=type, photo=url, heading=heading, description=description)
        #super(MediaDetailView, self).form_valid(form)
         #messages.success(request, 'Item created successfully!')
        form.save()

        return HttpResponseRedirect(reverse('solarpanel:list'))

class BannerUpdateView(LoginRequiredMixin,UpdateView):
    fields=('photo','heading','description')
    model = banner
    success_url = reverse_lazy('solarpanel:list')

class ProjectsUpdateView(LoginRequiredMixin,UpdateView):
    fields=('photo','heading','description')
    model = banner
    success_url = reverse_lazy('solarpanel:list')

class CareerUpdateView(LoginRequiredMixin,UpdateView):
    fields=('photo','heading','description','openings')
    model = banner
    success_url = reverse_lazy('solarpanel:list')

class TeamUpdateView(LoginRequiredMixin,UpdateView):
    fields=('photo','description','name','designation','linkfb','linkinsta','linklin')
    model = banner
    success_url = reverse_lazy('solarpanel:list')

class MediaUpdateView(LoginRequiredMixin,UpdateView):
    fields=('photo','heading','description')
    model = banner
    success_url = reverse_lazy('solarpanel:list')


class BannerDeleteView(LoginRequiredMixin,DeleteView):
    model = banner
    success_url = reverse_lazy('solarpanel:list')


class ProjectsDeleteView(LoginRequiredMixin,DeleteView):
    model = banner
    success_url = reverse_lazy('solarpanel:list')

class CareerDeleteView(LoginRequiredMixin,DeleteView):
    model = banner
    success_url = reverse_lazy('solarpanel:list')

class TeamDeleteView(LoginRequiredMixin,DeleteView):
    model = banner
    success_url = reverse_lazy('solarpanel:list')

class MediaDeleteView(LoginRequiredMixin,DeleteView):
    model = banner
    success_url = reverse_lazy('solarpanel:list')

solarpanel/templates/solarpanel/admin.html
{% extends 'base.html' %}

    {% block body_block %}
        <h1>For List of all sections Click on this</h1>
        <p><a href="{% url 'solarpanel:list' %}"> <h2>LIST</h2></a></p>

        <h1>For create view click on this</h1>
        <p><a href="{% url 'solarpanel:Banner' %}"> <h2>Banner</h2></a></p>
                <p><a href="{% url 'solarpanel:Project' %}"> <h2>Project</h2></a></p>
                <p><a href="{% url 'solarpanel:Career' %}"> <h2>Career</h2></a></p>
                <p><a href="{% url 'solarpanel:Team' %}"> <h2>Team</h2></a></p>
                <p><a href="{% url 'solarpanel:Media' %}"> <h2>Media</h2></a></p>

    {% endblock %}

solarpanel/templates/solarpanel/banner.html
{%  extends 'base.html' %}

    {% block body_block %}

         <form method="post" action="" enctype="multipart/form-data">

          {% csrf_token %}
         <p> <label>Add Photo</label>
             <input type="file" name="photo">
         </p>
         <p>
          <h1><label>Add heading</label></h1>
          <input type="text" name="heading" >
         </p>

          <p>
          <label>Add Description</label>
          <input type="text" name="description" >
          </p>

          <p>

          <input type="submit" name="submit" value="submit" >
          </p>



      </form>

    {% endblock %}

solarpanel/templates/solarpanel/banner_confirm_delete.html
{% extends 'base.html' %}

    {% block body_block %}
      <form method="post">
        {% csrf_token %}
      <p>{{ object.description }}</p>
          <p>{{ object.heading }}</p>
          <p>{{ object.photo }}</p>
          <p>{{ object.name }}</p>
        <button class="btn btn-primary" type="submit">Yes, remove it!</button>
  </form>
    {% endblock %}

solarpanel/templates/solarpanel/banner_form.html
{% extends 'base.html' %}

    {% block body_block %}
        <form method="post">
        {% csrf_token %}

        {{ form.as_p }}

        <input type="submit" value="update">

        </form>
    {% endblock %}

solarpanel/templates/solarpanel/career.html
{%  extends 'base.html' %}

    {% block body_block %}

         <form method="post" action="" enctype="multipart/form-data">

          {% csrf_token %}
         <p> <label>Add Icon</label>
             <input type="file" name="photo">
         </p>
         <p>
          <h1><label>Add heading</label></h1>
          <input type="text" name="heading" >
         </p>

          <p>
          <label>Add Description</label>
          <input type="text" name="description" >
          </p>

          <p>
          <label>No of openings</label>
          <input type="number" name="openings" >
          </p>

          <p>

          <input type="submit" name="submit" value="submit" >
          </p>



      </form>

    {% endblock %}

solarpanel/templates/solarpanel/content.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Content</title>
</head>
<body>
<h1> LIST ENJOY SURFURING</h1>

<h1>banner section</h1>
{% for c in con %}
{% if c.type is 1 %}
    <h1><a href="{% url 'solarpanel:contentdetail' pk=c.pk %}">{{ c.heading }} </a></h1>
 {% else %}
 {% endif %}
{% endfor %}

<h1>project section</h1>
{% for c in con %}
{% if c.type is 2 %}
<h1><a href="{% url 'solarpanel:contentdetail' pk=c.pk %}">{{ c.heading }} </a></h1>
{% else %}
{% endif %}
{% endfor %}

<h1>career section</h1>
{% for c in con %}
{% if c.type is 3 %}
<h1><a href="{% url 'solarpanel:contentdetail' pk=c.pk %}">{{ c.heading }} </a></h1>
{% else %}
{% endif %}
{% endfor %}


<h1>team section</h1>
{% for c in con %}
{% if c.type is 4 %}

<h1><a href="{% url 'solarpanel:contentdetail' pk=c.pk %}">{{ c.name }} </a></h1>
{% else %}
{% endif %}
{% endfor %}


<h1>media section</h1>
{% for c in con %}
{% if c.type is 5 %}
<h1><a href="{% url 'solarpanel:contentdetail' pk=c.pk %}">{{ c.heading }} </a></h1>
{% else %}
{% endif %}
{% endfor %}


</body>
</html>

solarpanel/templates/solarpanel/contentdetail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Content</title>
</head>
<body>
<h1> Detail </h1>



{% if c.type is 1 %}
<h1>banner section</h1>


<p>{{ c.description }}</p>
<p>{{ c.type }}</p>
    
<p><img src="{{ c.photo }}" alt=""></p>

<a href="{% url 'solarpanel:bannerupdate' pk=c.pk %}">UPDATE BANNER</a>
<a href="{% url 'solarpanel:bannerdelete' pk=c.pk %}">DELETE BANNER</a>
{% elif c.type is 2 %}

<h1>project section</h1>

{{ c.type }}
{{ c.description }}
<p><img src="{{ c.photo }}" alt=""></p>

<a href="{% url 'solarpanel:projectupdate' pk=c.pk %}">UPDATE PROJECT</a>
<a href="{% url 'solarpanel:projectdelete' pk=c.pk %}">DELETE PROJECT</a>

{% elif c.type is 3 %}

<h1>career section</h1>

{{ c.type }}
{{ c.description }}
<p><img src="{{ c.photo }}" alt=""></p>
<a href="{% url 'solarpanel:careerupdate' pk=c.pk %}">UPDATE CAREER</a>
<a href="{% url 'solarpanel:careerdelete' pk=c.pk %}">DELETE CAREER</a>

{% elif c.type is 4 %}

<h1>team section</h1>

{{ c.type }}
{{ c.name }}
<p><img src="{{ c.photo }}" alt=""></p>
<a href="{% url 'solarpanel:teamupdate' pk=c.pk %}">UPDATE TEAM MEMBER</a>
<a href="{% url 'solarpanel:teamdelete' pk=c.pk %}">DELETE TEAM MEMBER</a>


{% elif c.type is 5 %}

<h1>media section</h1>

{{ c.type }}
{{ c.name }}
<p><img src="{{ c.photo }}" alt=""></p>
<a href="{% url 'solarpanel:mediaupdate' pk=c.pk %}">UPDATE media</a>
<a href="{% url 'solarpanel:mediadelete' pk=c.pk %}">DELETE media</a>

{% endif %}

</body>
</html>

solarpanel/templates/solarpanel/media.html
{%  extends 'base.html' %}

    {% block body_block %}

         <form method="post" action="" enctype="multipart/form-data">

          {% csrf_token %}
         <p> <label>Add Photo</label>
             <input type="file" name="photo">
         </p>
         <p>
          <h1><label>Add heading</label></h1>
          <input type="text" name="heading" >
         </p>

          <p>
          <label>Add Description</label>
          <input type="text" name="description" >
          </p>

          <p>

          <input type="submit" name="submit" value="submit" >
          </p>



      </form>

    {% endblock %}

solarpanel/templates/solarpanel/project.html
{%  extends 'base.html' %}

    {% block body_block %}

         <form method="post" action="" enctype="multipart/form-data">

          {% csrf_token %}
         <p> <label>Add Photo</label>
             <input type="file" name="photo">
         </p>
         <p>
          <h1><label>Add heading</label></h1>
          <input type="text" name="heading" >
         </p>

          <p>
          <label>Add Description</label>
          <input type="text" name="description" >
          </p>

          <p>

          <input type="submit" name="submit" value="submit" >
          </p>



      </form>

    {% endblock %}

solarpanel/templates/solarpanel/projectupdate.html
{% extends 'base.html' %}

    {% block body_block %}
        <form method="post">
        {% csrf_token %}

        {{ form.as_p }}

        <input type="submit" value="update">

        </form>
    {% endblock %}

solarpanel/templates/solarpanel/team.html
{%  extends 'base.html' %}

    {% block body_block %}

         <form method="post" action="" enctype="multipart/form-data">

          {% csrf_token %}
         <p> <label>Add Photo</label>
             <input type="file" name="photo">
         </p>
         <p>
          <h1><label>Name</label></h1>
          <input type="text" name="name" >
         </p>

          <p>
          <label>Add Description</label>
          <input type="text" name="description" >
          </p>

          <p>
          <label>Fb link</label>
          <input type="text" name="linkfb" >
          </p>

           <p>
          <label>Insta Link</label>
          <input type="text" name="linkinsta" >
         </p>

          <p>
          <label>Linkedin Link</label>
          <input type="text" name="linklin" >
          </p>

          <p>
          <label>Designation</label>
          <input type="text" name="designation" >
          </p>

          <p>

          <input type="submit" name="submit" value="submit" >
          </p>



      </form>

    {% endblock %}